spring:
  application:
    name: todo-reports

server:
  port: 8030


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8028/eureka/
  instance:
    hostname: localhost