spring:
  application:
    name: todo-manager

server:
  port: 8029


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8028/eureka/
  instance:
    hostname: localhost